### ISSUE TITLE
Separate machinery and machinery_phoenix library

### ISSUE THREAD

**Issue by pradosh987** [joaomdmoura/machinery#37]
Machinery right now makes it difficult to use it with non-phoenix projects because of its hard dependency on phoenix and ecto, also its not Phoenix 1.4 and ecto 3.0 compatible yet. I think splitting machinery into two packages **machinery** and **machinery_phoenix**/**machinery_webui** will improve its flexibility. Ecto itself has done it with "ecto" and "ecto_sql". Do you think it would be worth refactoring ?

**Comment by joaomdmoura** [comment]
Seems reasonable, I also don't like the fact of having this huge dependency when building smalle state machines, something that might be worth doing indeed for the next release

**Comment by pradosh987** [comment]
Machinery has more or less all the required features. I'll suggest forking this version into bare state machine without Ecto and phoenix and see how its adopted. That should amount to minimal work and also providing usage stats of both versions. Also upgrading Web ui will require more time because of phoenix 1.4 and other dependencies.

**Comment by atonse** [comment]
I've started on this. https://github.com/atonse/machinery

I've got all tests passing. I'll have to create a separate web_ui repo to put all the phoenix stuff in there.

**Comment by joaomdmoura** [comment]
This is done folks, I merged the PR and removed the rest into another, closing this, will try to release a new version soon
