### ISSUE TITLE
Machinery should work with Phoenix 1.4 (Cowboy 2.5, Ecto 3.0)

### ISSUE THREAD

**Issue by felbit** [joaomdmoura/machinery#40]
Phoenix 1.4 is released and we are working with this version of Phoenix. We would also like to continue working with machinery, but it complains about Cowboy and Ecto.

**Comment by wronfim** [comment]
@MarPenc Seems like it's fixed in master.

So, While we wait on the next release, try to install it from Github directly:
```elixir
{:machinery, git: "https://github.com/joaomdmoura/machinery.git"}
```

**Comment by joaomdmoura** [comment]
@MarPenc I'll update it accordingly and release a new version this week still :smile:

**Comment by MarPenc** [comment]
> @MarPenc I'll update it accordingly and release a new version this week still 😄

That would be awesome. Thank you for your work!

**Comment by felbit** [comment]
@joaomdmoura  That would be awesome. Thank you for your work!

**Comment by joaomdmoura** [comment]
Just letting you all know I'm still working on this, trying to to update everything to the edge, but it is requiring some refactoring, I'm currently 10 tests away of getting it done :smile:

**Comment by joaomdmoura** [comment]
made a new release with ecto 3.0, working on updating the remaining dependencies

**Comment by beno** [comment]
Still a problem with cowboy 2, I need to add

    {:cowboy, "~> 2.5", override: true},

to my mix file to make it work with machinery.

**Comment by sobolevn** [comment]
How is the status of this issue? Still does not work with the latest version of `phoenix` by default.

**Comment by elbasti** [comment]
When I try to use the machinery web interface on Phoenix 1.4 I get the following error:

> function Phoenix.Router.Route.forward/4 is undefined or private

from `/lib/machinery/plug.ex:53`

I was able to install machinery by forcing cowboy 2.5 w/ `override: true`

**Comment by mmendez512** [comment]
It's been a few months, are you going to release it soon?

**Comment by simaofreitas** [comment]
Bump. Having the same issue :(

**Comment by antonioparisi** [comment]
@joaomdmoura any update on this?

**Comment by Dan1one** [comment]
@joaomdmoura  Yo! Still not working! Should we try to fix it? Whats the way fork it and make it work? Do you have tests on it working with the new Plug/cowboy combination? How do we split it? should we brake compatibility with old versions of phoenix?

**Comment by joaomdmoura** [comment]
Hey everyone! I've spend some time last couple days updating Machinery and getting some PRs merged.Some code got removed and some fixes were merged.

As part of this new version I'll be removing the dependency on Phoenix (and the live dashboard included by default), it was a huge dependency for a small library and it shouldn't be hard to people to built it in their apps themselves once they have all this data in the database already.

I just tested master with the newest version of Phoenix and it works like a charm! No conflicts at all, everything seems to be working fine.

So if you want to give that a try go ahead, I'll make a few more tests before cutting a new version, until then I'll keep this open just in case there are any bugs. Again master should work fine for everyone but there is no more live dashboard included. Thanks for all the patience on this 😅

**Comment by joaomdmoura** [comment]
Folks, happy to announce I just release version 1.0.0.
https://hex.pm/packages/machinery

It's a 1.0.0 because of all the breaking changes it has, like removing the dashboard feature a dependency on phoenix.

Closing this for now, let me know if you find any bugs.
