### ISSUE TITLE
Mix test fails with a specific seed

### ISSUE THREAD

**Issue by DanielePalombo** [joaomdmoura/machinery#44]
Hi I see that  `mix test --seed=244405` fails with:

```
Finished in 0.3 seconds
45 tests, 15 failures, 11 invalid

Randomized with seed 244405
```

I'm investigating on it, if anyone have some ideas to fix them, is welcome.

**Comment by joaomdmoura** [comment]
Yup indeed it seems there is a problem with intermittent tests, I'm also doing some overall investigation to see where it leads to

**Comment by joaomdmoura** [comment]
@DanielePalombo thanks again for this, it was fixed in https://github.com/joaomdmoura/machinery/pull/50
