### ISSUE TITLE
User-specified `field` is not respected

### ISSUE THREAD

**Issue by elbasti** [joaomdmoura/machinery#52]
If a user specifies a `field` attribute in the state machine module, the field is not used in the web interface. 

The [ecto query](https://github.com/joaomdmoura/machinery/blob/a68681ee70ea19da65efdbf3308a6cdd3970cf35/lib/web/controllers/resource_controller.ex#L57) used in the web interface is hardcoded to `state`.

**Comment by elbasti** [comment]
I believe I've fixed the issue in this pr: https://github.com/joaomdmoura/machinery/pull/53

**Comment by joaomdmoura** [comment]
Dropping the web interface for the next version.
