### ISSUE TITLE
Why a genserver?

### ISSUE THREAD

**Issue by naps62** [joaomdmoura/machinery#72]
I'm using this package for the first time. First of all, thank you for the work put into it :+1: 

I'm not currently understanding why this is built as a GenServer. It seems one is started for every state machine module created, but it seems that's only used as a way to keep the parameters as state.

I would have expected to find this being done as module attributes and module variables. Why was that not the approach followed here?

**Comment by jwbrew** [comment]
Related; this is preventing me from being able to include state transitions in transaction blocks with ecto. Because the update is executed in a different process it causes the request to hang. Sample:

```
  def update_version(%Version{} = version, %{state: state} = attrs) do
    #  We'd like to run this in a transaction, but Machinery runs the peristence
    # in a separate process so transactions hang

    with {:ok, version} <-
           version |> Version.changeset(attrs) |> Repo.update(),
         {:ok, version} <- Machinery.transition_to(version, Codex.VersionStateMachine, state) do
      {:ok, version}
    end
  end
```

**Comment by naps62** [comment]
@jwbrew I ended up building my own package, because I was suffering from the same issue as you did (and I also wanted to be able to process state transitions, and callbacks, within an `Ecto.Multi`)

you seem to have a similar use-case, so check it out https://github.com/subvisual/fsmx

PS: I don't mean this as some sort of shameless marketing. I'm highly grateful to this package's author, it just didn't fit my own purposes, so I built my own. Hopefully this is not taken in the wrong way :slightly_smiling_face:

**Comment by joaomdmoura** [comment]
Hey folks, gotta say I don't really recall the reasoning behind making this call back in 2016 😅 

I'm fine with any new proposals tho, even tho  I'm not using this library in any current project we can talk it through and implement it together so we can all make this better for the other people using it as well.
